[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold   = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size   = 9

[window]
padding.x   = 14
padding.y   = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift",   action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy"  },
]

# Gruvbox theme
[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.cursor]
text   = "#282828"
cursor = "#bdae93"

[colors.selection]
text       = "#ebdbb2"
background = "#d65d0e"

[colors.normal]
black   = "#3c3836"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#3c3836"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"
